/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ParticlesToBBDD_constants.h"

namespace BBDDParticles {

const ParticlesToBBDDConstants g_ParticlesToBBDD_constants;

ParticlesToBBDDConstants::ParticlesToBBDDConstants() {
}

} // namespace

