/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ParticlesToBBDD_H
#define ParticlesToBBDD_H

#include <thrift/TDispatchProcessor.h>
#include "ParticlesToBBDD_types.h"

namespace BBDDParticles {

class ParticlesToBBDDIf {
 public:
  virtual ~ParticlesToBBDDIf() {}
  virtual void insertParticles(InsertResult& _return, const InsertData& data) = 0;
  virtual int32_t ping() = 0;
};

class ParticlesToBBDDIfFactory {
 public:
  typedef ParticlesToBBDDIf Handler;

  virtual ~ParticlesToBBDDIfFactory() {}

  virtual ParticlesToBBDDIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ParticlesToBBDDIf* /* handler */) = 0;
};

class ParticlesToBBDDIfSingletonFactory : virtual public ParticlesToBBDDIfFactory {
 public:
  ParticlesToBBDDIfSingletonFactory(const boost::shared_ptr<ParticlesToBBDDIf>& iface) : iface_(iface) {}
  virtual ~ParticlesToBBDDIfSingletonFactory() {}

  virtual ParticlesToBBDDIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ParticlesToBBDDIf* /* handler */) {}

 protected:
  boost::shared_ptr<ParticlesToBBDDIf> iface_;
};

class ParticlesToBBDDNull : virtual public ParticlesToBBDDIf {
 public:
  virtual ~ParticlesToBBDDNull() {}
  void insertParticles(InsertResult& /* _return */, const InsertData& /* data */) {
    return;
  }
  int32_t ping() {
    int32_t _return = 0;
    return _return;
  }
};

typedef struct _ParticlesToBBDD_insertParticles_args__isset {
  _ParticlesToBBDD_insertParticles_args__isset() : data(false) {}
  bool data :1;
} _ParticlesToBBDD_insertParticles_args__isset;

class ParticlesToBBDD_insertParticles_args {
 public:

  static const char* ascii_fingerprint; // = "941B1A43417789C42803BF39EE718F5A";
  static const uint8_t binary_fingerprint[16]; // = {0x94,0x1B,0x1A,0x43,0x41,0x77,0x89,0xC4,0x28,0x03,0xBF,0x39,0xEE,0x71,0x8F,0x5A};

  ParticlesToBBDD_insertParticles_args(const ParticlesToBBDD_insertParticles_args&);
  ParticlesToBBDD_insertParticles_args& operator=(const ParticlesToBBDD_insertParticles_args&);
  ParticlesToBBDD_insertParticles_args() {
  }

  virtual ~ParticlesToBBDD_insertParticles_args() throw();
  InsertData data;

  _ParticlesToBBDD_insertParticles_args__isset __isset;

  void __set_data(const InsertData& val);

  bool operator == (const ParticlesToBBDD_insertParticles_args & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    return true;
  }
  bool operator != (const ParticlesToBBDD_insertParticles_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ParticlesToBBDD_insertParticles_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_insertParticles_args& obj);
};


class ParticlesToBBDD_insertParticles_pargs {
 public:

  static const char* ascii_fingerprint; // = "941B1A43417789C42803BF39EE718F5A";
  static const uint8_t binary_fingerprint[16]; // = {0x94,0x1B,0x1A,0x43,0x41,0x77,0x89,0xC4,0x28,0x03,0xBF,0x39,0xEE,0x71,0x8F,0x5A};


  virtual ~ParticlesToBBDD_insertParticles_pargs() throw();
  const InsertData* data;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_insertParticles_pargs& obj);
};

typedef struct _ParticlesToBBDD_insertParticles_result__isset {
  _ParticlesToBBDD_insertParticles_result__isset() : success(false) {}
  bool success :1;
} _ParticlesToBBDD_insertParticles_result__isset;

class ParticlesToBBDD_insertParticles_result {
 public:

  static const char* ascii_fingerprint; // = "C398A628D47A730227A6ADC2F08E5334";
  static const uint8_t binary_fingerprint[16]; // = {0xC3,0x98,0xA6,0x28,0xD4,0x7A,0x73,0x02,0x27,0xA6,0xAD,0xC2,0xF0,0x8E,0x53,0x34};

  ParticlesToBBDD_insertParticles_result(const ParticlesToBBDD_insertParticles_result&);
  ParticlesToBBDD_insertParticles_result& operator=(const ParticlesToBBDD_insertParticles_result&);
  ParticlesToBBDD_insertParticles_result() {
  }

  virtual ~ParticlesToBBDD_insertParticles_result() throw();
  InsertResult success;

  _ParticlesToBBDD_insertParticles_result__isset __isset;

  void __set_success(const InsertResult& val);

  bool operator == (const ParticlesToBBDD_insertParticles_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ParticlesToBBDD_insertParticles_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ParticlesToBBDD_insertParticles_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_insertParticles_result& obj);
};

typedef struct _ParticlesToBBDD_insertParticles_presult__isset {
  _ParticlesToBBDD_insertParticles_presult__isset() : success(false) {}
  bool success :1;
} _ParticlesToBBDD_insertParticles_presult__isset;

class ParticlesToBBDD_insertParticles_presult {
 public:

  static const char* ascii_fingerprint; // = "C398A628D47A730227A6ADC2F08E5334";
  static const uint8_t binary_fingerprint[16]; // = {0xC3,0x98,0xA6,0x28,0xD4,0x7A,0x73,0x02,0x27,0xA6,0xAD,0xC2,0xF0,0x8E,0x53,0x34};


  virtual ~ParticlesToBBDD_insertParticles_presult() throw();
  InsertResult* success;

  _ParticlesToBBDD_insertParticles_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_insertParticles_presult& obj);
};


class ParticlesToBBDD_ping_args {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};

  ParticlesToBBDD_ping_args(const ParticlesToBBDD_ping_args&);
  ParticlesToBBDD_ping_args& operator=(const ParticlesToBBDD_ping_args&);
  ParticlesToBBDD_ping_args() {
  }

  virtual ~ParticlesToBBDD_ping_args() throw();

  bool operator == (const ParticlesToBBDD_ping_args & /* rhs */) const
  {
    return true;
  }
  bool operator != (const ParticlesToBBDD_ping_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ParticlesToBBDD_ping_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_ping_args& obj);
};


class ParticlesToBBDD_ping_pargs {
 public:

  static const char* ascii_fingerprint; // = "99914B932BD37A50B983C5E7C90AE93B";
  static const uint8_t binary_fingerprint[16]; // = {0x99,0x91,0x4B,0x93,0x2B,0xD3,0x7A,0x50,0xB9,0x83,0xC5,0xE7,0xC9,0x0A,0xE9,0x3B};


  virtual ~ParticlesToBBDD_ping_pargs() throw();

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_ping_pargs& obj);
};

typedef struct _ParticlesToBBDD_ping_result__isset {
  _ParticlesToBBDD_ping_result__isset() : success(false) {}
  bool success :1;
} _ParticlesToBBDD_ping_result__isset;

class ParticlesToBBDD_ping_result {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};

  ParticlesToBBDD_ping_result(const ParticlesToBBDD_ping_result&);
  ParticlesToBBDD_ping_result& operator=(const ParticlesToBBDD_ping_result&);
  ParticlesToBBDD_ping_result() : success(0) {
  }

  virtual ~ParticlesToBBDD_ping_result() throw();
  int32_t success;

  _ParticlesToBBDD_ping_result__isset __isset;

  void __set_success(const int32_t val);

  bool operator == (const ParticlesToBBDD_ping_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ParticlesToBBDD_ping_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ParticlesToBBDD_ping_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_ping_result& obj);
};

typedef struct _ParticlesToBBDD_ping_presult__isset {
  _ParticlesToBBDD_ping_presult__isset() : success(false) {}
  bool success :1;
} _ParticlesToBBDD_ping_presult__isset;

class ParticlesToBBDD_ping_presult {
 public:

  static const char* ascii_fingerprint; // = "32183C4A04E706C58ED2F62566DDD8DE";
  static const uint8_t binary_fingerprint[16]; // = {0x32,0x18,0x3C,0x4A,0x04,0xE7,0x06,0xC5,0x8E,0xD2,0xF6,0x25,0x66,0xDD,0xD8,0xDE};


  virtual ~ParticlesToBBDD_ping_presult() throw();
  int32_t* success;

  _ParticlesToBBDD_ping_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

  friend std::ostream& operator<<(std::ostream& out, const ParticlesToBBDD_ping_presult& obj);
};

class ParticlesToBBDDClient : virtual public ParticlesToBBDDIf {
 public:
  ParticlesToBBDDClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ParticlesToBBDDClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void insertParticles(InsertResult& _return, const InsertData& data);
  void send_insertParticles(const InsertData& data);
  void recv_insertParticles(InsertResult& _return);
  int32_t ping();
  void send_ping();
  int32_t recv_ping();
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ParticlesToBBDDProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ParticlesToBBDDIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ParticlesToBBDDProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_insertParticles(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_ping(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ParticlesToBBDDProcessor(boost::shared_ptr<ParticlesToBBDDIf> iface) :
    iface_(iface) {
    processMap_["insertParticles"] = &ParticlesToBBDDProcessor::process_insertParticles;
    processMap_["ping"] = &ParticlesToBBDDProcessor::process_ping;
  }

  virtual ~ParticlesToBBDDProcessor() {}
};

class ParticlesToBBDDProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ParticlesToBBDDProcessorFactory(const ::boost::shared_ptr< ParticlesToBBDDIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ParticlesToBBDDIfFactory > handlerFactory_;
};

class ParticlesToBBDDMultiface : virtual public ParticlesToBBDDIf {
 public:
  ParticlesToBBDDMultiface(std::vector<boost::shared_ptr<ParticlesToBBDDIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ParticlesToBBDDMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ParticlesToBBDDIf> > ifaces_;
  ParticlesToBBDDMultiface() {}
  void add(boost::shared_ptr<ParticlesToBBDDIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void insertParticles(InsertResult& _return, const InsertData& data) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->insertParticles(_return, data);
    }
    ifaces_[i]->insertParticles(_return, data);
    return;
  }

  int32_t ping() {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->ping();
    }
    return ifaces_[i]->ping();
  }

};

} // namespace

#endif
