# ALYA Witness set results
#
# HEADER
# ISET , Column :   1
# VELOX , Column :   2
# VELOY , Column :   3
# VELOZ , Column :   4
# PRESS , Column :   5
# NUMVARIABLES :       5
# NUMSETS      :       1
# START
# Iterations  =       0      0      0
# Time        =  0.00000000E+000
         1  0.50000000E+002  0.00000000E+000  0.00000000E+000  0.00000000E+000 
