#------------------------------------------------------------------- 
# 
#    alya2pos compilation file  
#    Automatically generated by configure  
#      Thu Sep  7 23:49:31 EDT 2023
# 
#------------------------------------------------------------------- 
# 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/def_kintyp.f90   -o ../../Utils/user/alya2pos/def_kintyp.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/def_elmtyp.f90   -o ../../Utils/user/alya2pos/def_elmtyp.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/def_inpout.f90   -o ../../Utils/user/alya2pos/def_inpout.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/mod_maths.f90    -o ../../Utils/user/alya2pos/mod_maths.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/mod_output.f90   -o ../../Utils/user/alya2pos/mod_output.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/txtres.f90       -o ../../Utils/user/alya2pos/txtres.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/gidres_he.f90    -o ../../Utils/user/alya2pos/gidres_he.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/gidres_gp.f90    -o ../../Utils/user/alya2pos/gidres_gp.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/elmtyp.f90       -o ../../Utils/user/alya2pos/elmtyp.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ecoute.f90       -o ../../Utils/user/alya2pos/ecoute.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/runend.f90       -o ../../Utils/user/alya2pos/runend.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/connpo.f90       -o ../../Utils/user/alya2pos/connpo.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/vu_msh.f90       -o ../../Utils/user/alya2pos/vu_msh.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/vu_res.f90       -o ../../Utils/user/alya2pos/vu_res.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/vu_filter.f90    -o ../../Utils/user/alya2pos/vu_filter.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensmsh.f90       -o ../../Utils/user/alya2pos/ensmsh.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensres.f90       -o ../../Utils/user/alya2pos/ensres.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/wristl.f90       -o ../../Utils/user/alya2pos/wristl.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensmsh_bin.f90       -o ../../Utils/user/alya2pos/ensmsh_bin.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensres_bin.f90       -o ../../Utils/user/alya2pos/ensres_bin.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensmsh_filter.f90       -o ../../Utils/user/alya2pos/ensmsh_filter.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/ensres_filter.f90       -o ../../Utils/user/alya2pos/ensres_filter.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/zfemres.f90       -o ../../Utils/user/alya2pos/zfemres.o 
  mpif90 -module ../../Utils/user/alya2pos -c  -fpp ../../Utils/user/alya2pos/reahed.f90       -o ../../Utils/user/alya2pos/reahed.o 
  mpif90   ../../Utils/user/alya2pos/alya2pos.f90 ../../Utils/user/alya2pos/*.o -o ../../Utils/user/alya2pos/alya2pos.x 
     rm  ../../Utils/user/alya2pos/*.o ../../Utils/user/alya2pos/*.mod 
