message(STATUS "Compiling with GNU")
set(CMAKE_Fortran_COMPILER mpif90)
set(CUSTOM_Fortran_FLAGS "-Wall -x f95-cpp-input -ffree-line-length-none -fimplicit-none")
set(CUSTOM_Fortran_FLAGS_RELEASE "")
set(CUSTOM_Fortran_FLAGS_DEBUG "-fbounds-check -fbacktrace -ftrapv -Wconversion-extra -g")
set(CUSTOM_Fortran_FLAGS_I4 "")
set(CUSTOM_Fortran_FLAGS_I8 "-m64")
set(CUSTOM_Fortran_FLAGS_O0 "-O0")
set(CUSTOM_Fortran_FLAGS_O1 "-O1")
set(CUSTOM_Fortran_FLAGS_O2 "-O2")
set(CUSTOM_Fortran_FLAGS_O3 "-O3")
set(CUSTOM_Fortran_FLAGS_STD2008 "-std=f2008")
