message(STATUS "Compiling with Intel")
set(CMAKE_Fortran_COMPILER mpif90)
set(CUSTOM_Fortran_FLAGS "-fpp")
set(CUSTOM_Fortran_FLAGS_RELEASE "")
set(CUSTOM_Fortran_FLAGS_DEBUG "-ftrapuv -check all,noarg_temp_created -traceback -debug full -warn all,nodec,nointerfaces -fp-stack-check -ansi-alias -g")
set(CUSTOM_Fortran_FLAGS_I4 "")
set(CUSTOM_Fortran_FLAGS_I8 "-m64")
set(CUSTOM_Fortran_FLAGS_ARCHITECTURE "-xCORE-AVX512 -mtune=skylake")
set(CUSTOM_Fortran_FLAGS_IPO "-ipo")
set(CUSTOM_Fortran_FLAGS_CODE_COVERAGE "-prof-gen=srcpos")
set(CUSTOM_Fortran_FLAGS_O0 "-O0")
set(CUSTOM_Fortran_FLAGS_O1 "-O1")
set(CUSTOM_Fortran_FLAGS_O2 "-O2")
set(CUSTOM_Fortran_FLAGS_O3 "-O3")
set(CUSTOM_Fortran_FLAGS_STD2008 "-std08")
