message(STATUS "Compiling with PGI")
set(CMAKE_Fortran_COMPILER "OMPI_FC=pgfortran mpif90")
set(CUSTOM_Fortran_FLAGS "-fast -Minfo=all -Mpreprocess -Mbackslash -Mextend -Mnoopenmp -Munroll -Mnoidiom")
set(CUSTOM_Fortran_FLAGS_RELEASE "")
set(CUSTOM_Fortran_FLAGS_DEBUG "")
set(CUSTOM_Fortran_FLAGS_I4 "")
set(CUSTOM_Fortran_FLAGS_I8 "")
set(CUSTOM_Fortran_FLAGS_O0 "-O0")
set(CUSTOM_Fortran_FLAGS_O1 "-O1")
set(CUSTOM_Fortran_FLAGS_O2 "-O2")
set(CUSTOM_Fortran_FLAGS_O3 "-O3")
set(CUSTOM_Fortran_FLAGS_STD2008 "")
