message(STATUS "Compiling with XL")
set(CMAKE_Fortran_COMPILER "mpif90")
set(CUSTOM_C_FLAGS "-qflag=i -DNOUNDERSCORE")
set(CUSTOM_Fortran_FLAGS "-qflag=i -qnoescape -qextname=flush:etime -qfree=f90 -qsuffix=cpp=f90 -qextname -qxlf2003=polymorphic")
set(CUSTOM_Fortran_FLAGS_RELEASE "")
set(CUSTOM_Fortran_FLAGS_DEBUG "")
set(CUSTOM_Fortran_FLAGS_I4 "")
set(CUSTOM_Fortran_FLAGS_I8 "")
set(CUSTOM_Fortran_FLAGS_O0 "-O0")
set(CUSTOM_Fortran_FLAGS_O1 "-O1")
set(CUSTOM_Fortran_FLAGS_O2 "-O2")
set(CUSTOM_Fortran_FLAGS_O3 "-O3")
set(CUSTOM_Fortran_FLAGS_STD2008 "-DFORTRAN_STD")
