ROOT         :=$(shell pwd)

wrappers:  
	@$(MAKE) -C $(ROOT)/Wrappers/FORTRAN  canteratest ROOT_CANTERA=$(ROOT_CANTERA) -B   


# test02 HOME=$(ROOT_CANTERA) ROOT_PLE=$(ROOT_CANTERA)/Execs CPPCOMPILER=mpicxx CCOMPILER=mpicc FCOMPILER=mpif90   



