subroutine ada_outaly
!-----------------------------------------------------------------------
!****f* adapti/ada_outaly
! NAME 
!    ada_outaly
! DESCRIPTION
!    This routine writes the dom.geo and fix files for the next round
! USES
!
! USED BY
!
!***
!-----------------------------------------------------------------------
  use      def_parame
  use      def_master
  use      def_domain
  use      def_inpout
  use      def_adapti
  implicit none
  integer(ip)              :: &
       lutmp,ielem,ipoin,jpoin,inode,itrce,iolne,lnofa(mnode),jelem,jolne

  if (nimmo_ada == 0) then
     !
     ! No immersed objects around here
     !

     ! DomDat file:
     write(lun_aldom_ada,'(a)') '$-------------------------------------------------'
     write(lun_aldom_ada,'(a)') '$----DomDat file automatically generated by ADAPTI'
     write(lun_aldom_ada,'(a)') '$-------------------------------------------------'
     write(lun_aldom_ada,'(a)') 'DIMENSIONS'
     write(lun_aldom_ada,150) '   NODAL_POINTS =' , npnew_ada
     write(lun_aldom_ada,150) '   ELEMENTS     =' , nenew_ada
     write(lun_aldom_ada,150) '   SPACE_DIM    =' , ndime
     write(lun_aldom_ada,150) '   NODES        =' , mnode
     write(lun_aldom_ada,150) '   BOUNDARIES   =' , nboun
     write(lun_aldom_ada,'(a)') '   NO_SETS'
     write(lun_aldom_ada,'(a)') 'END_DIMENSIONS'
     write(lun_aldom_ada,'(a)') 'STRATEGY'
     write(lun_aldom_ada,'(a)') '   DOMAIN_INTEG_POINTS=   1'
     write(lun_aldom_ada,'(a)') '   WRITE_EXT_NORMAL   =  NO'
     write(lun_aldom_ada,'(a)') '   OUTPUT_MESH_DATA   = YES'
     write(lun_aldom_ada,'(a)') 'END_STRATEGY'
     write(lun_aldom_ada,'(a)') 'GEOMETRY , GID'
     write(lun_aldom_ada,200) '   INCLUDE  ',adjustl(trim(fil_algeo_ada))
     write(lun_aldom_ada,'(a)') 'END_GEOMETRY'
     write(lun_aldom_ada,'(a)') 'SETS'
     write(lun_aldom_ada,'(a)') 'END_SETS'

     ! DomGeo file:
     write(lun_algeo_ada,'(a)') 'ELEMENTS'  
     do ielem = 1,nenew_ada
        write(lun_algeo_ada,*) ielem, (lnnew_ada(inode,ielem),inode=1,mnode)
     end do
     write(lun_algeo_ada,'(a)') 'END_ELEMENTS'
     write(lun_algeo_ada,'(a)') 'COORDINATES'  
     do ipoin= 1,npoin
        write(lun_algeo_ada,*) ipoin, coord(1:ndime,ipoin)
     end do
     jpoin= 0
     do ipoin= npoin+1, npnew_ada
        jpoin= jpoin+1
        write(lun_algeo_ada,*) ipoin, conew_ada(1:ndime,jpoin)
     end do
     write(lun_algeo_ada,'(a)') 'END_COORDINATES'  

  else if (nimmo_ada > 0) then
     !
     ! Immersed objects are present
     !

     !
     ! Falta esteeeeee ojoooooooo
     !     


  end if

150 format(a,2x,i12)
200 format(a,4x,a)
     

end subroutine ada_outaly
