function(init_cantera)
  set(CANTERA_INCLUDE_DIR "${CANTERA_DIR}/include" CACHE INTERNAL "")
  set(CANTERA_INCLUDE_CANTERA_DIR "${CANTERA_INCLUDE_DIR}/cantera" CACHE INTERNAL "")
  set(CANTERA_LIB_DIR ${CANTERA_DIR}/lib CACHE INTERNAL "")
endfunction()

function(cantera)
  if (WITH_CANTERA MATCHES "external")
    if (NOT PROJECT_NAME MATCHES cantera_fwrapper)
      add_dependencies(${PROJECT_NAME} cantera_fwrapper)
      add_definitions(-DCANTERA=1)
      target_link_libraries(${PROJECT_NAME} cantera_fwrapper)
    endif()
    include_directories(${CANTERA_INCLUDE_DIR} ${CANTERA_INCLUDE_CANTERA_DIR})
    link_directories(${CANTERA_LIB_DIR})
    if (CANTERA_DIR STREQUAL "")
      target_link_libraries(${PROJECT_NAME} libcantera_fortran.a libcantera.a)
    else()
      target_link_libraries(${PROJECT_NAME} ${CANTERA_LIB_DIR}/libcantera_fortran.a ${CANTERA_LIB_DIR}/libcantera.a)
    endif()
  endif()
endfunction()
