function(init_metis)
  set(ASSERT OFF CACHE INTERNAL "")
  set(ASSERT2 OFF CACHE INTERNAL "")
  set(DEBUG OFF CACHE INTERNAL "")
  set(GDB OFF CACHE INTERNAL "")
  set(GKRAND OFF CACHE INTERNAL "")
  set(GKREGEX OFF CACHE INTERNAL "")
  set(GPROF OFF CACHE INTERNAL "")
  set(METIS_REAL "64" CACHE INTERNAL "")
  set(OPENMP OFF CACHE INTERNAL "")
  if (INTEGER_SIZE MATCHES "4")
    set(METIS_INTEGER "32" CACHE INTERNAL "")
  elseif (INTEGER_SIZE MATCHES "8")
    set(METIS_INTEGER "64" CACHE INTERNAL "")
  endif()
endfunction()

function(metis)
  if (NOT WITH_METIS MATCHES "OFF")
    add_definitions(-DV51METIS)
    include_directories(${METIS_INCLUDE_DIR})
    target_link_libraries(${PROJECT_NAME} metis)
  endif()
endfunction()
