foreach(MOD ${MODULES})
  string(TOUPPER ${MOD} UPMOD)
  if(WITH_MODULE_${UPMOD})
    message(STATUS "Module ${MOD} enabled.")
    add_definitions(-D'${UPMOD}_MODULE=use')
    set(MODU ${MOD}_MODULE_DIR)
    list(APPEND MODULES_MODULE_DIR ${${MODU}})
    list(APPEND MODULES_LIB ${MOD})
  endif()
endforeach()
