function(init_mpi)
  if (WITH_MPI)
    find_package(MPI)
    if (NOT MPI_FOUND)
      message(FATAL_ERROR "MPI not found!")
    elseif (NOT MPI_Fortran_FOUND)
      message(STATUS "MPI Fortran not found! You can ignore this warning unless errors occur during the build.")
      set(MPI_Fortran_FOUND TRUE)
    else()
      message("MPI found!")
    endif()
  else()
    message(WARNING "MPI disabled!")
  endif()
endfunction()

function(include_directories_mpi)
  if (WITH_MPI)
    include_directories(${MPI_Fortran_INCLUDE_PATH})
  endif()
endfunction()

function(include_directories_mpi_c)
  if (WITH_MPI)
    include_directories(${MPI_C_INCLUDE_PATH})
  endif()
endfunction()

function(include_directories_mpi_cxx)
  if (WITH_MPI)
    include_directories(${MPI_CXX_INCLUDE_PATH})
  endif()
endfunction()

function(target_link_libraries_mpi)
  if (WITH_MPI)
    target_link_libraries(${PROJECT_NAME} ${MPI_Fortran_LIBRARIES})
    if(MPI_COMPILE_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "${MPI_COMPILE_FLAGS}")
    endif()
    if(MPI_LINK_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${MPI_LINK_FLAGS}")
    endif()
  endif()
endfunction()

function(target_link_libraries_mpi_c)
  if (WITH_MPI)
    target_link_libraries(${PROJECT_NAME} ${MPI_C_LIBRARIES})
    if(MPI_COMPILE_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "${MPI_COMPILE_FLAGS}")
    endif()
    if(MPI_LINK_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${MPI_LINK_FLAGS}")
    endif()
  endif()
endfunction()

function(target_link_libraries_mpi_cxx)
  if (WITH_MPI)
    target_link_libraries(${PROJECT_NAME} ${MPI_C_LIBRARIES})
    if(MPI_COMPILE_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES COMPILE_FLAGS "${MPI_COMPILE_FLAGS}")
    endif()
    if(MPI_LINK_FLAGS)
      set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "${MPI_LINK_FLAGS}")
    endif()
  endif()
endfunction()
