function(init_talp)
  set(DLB_INCLUDE_DIR "${DLB_DIR}/include" CACHE INTERNAL "")
  set(DLB_LIB_DIR "${DLB_DIR}/lib" CACHE INTERNAL "")
endfunction()

function(talp)
  if (WITH_DLB_TALP MATCHES "external")
    add_definitions(-DALYA_TALP)
    include_directories(${DLB_INCLUDE_DIR})
    link_directories(${DLB_LIB_DIR})
    if (DLB_DIR STREQUAL "")
      target_link_libraries(${PROJECT_NAME} libdlb.so)
    else()
      target_link_libraries(${PROJECT_NAME} ${DLB_LIB_DIR}/libdlb.so)
      set_target_properties(${PROJECT_NAME} PROPERTIES INSTALL_RPATH "${DLB_LIB_DIR}")
      set_target_properties(${PROJECT_NAME} PROPERTIES BUILD_WITH_INSTALL_RPATH ON)
    endif()
  endif()
endfunction()
