#!/bin/bash 

echo 
echo '--| alya-rename |-- '
echo '--| '
if  [ "$1" = "-h" ] || [ "$1" = "-help" ] || [ "$1" = "" ]; then
echo '--| Substitute module extension names of files'
echo '--| '
echo '--| Usage:   alya-module ext1 ext2'
echo '--|'
echo '--| ext1 ... Initital extension'
echo '--| ext2 ... Final extension'
echo '--| '
echo '--| Bye.'
echo '--| '
echo '--| '
exit
else
echo '--| Substituing extensions of files'
echo '--| '$1_*' <- '$2_*' '
fi

FILES=(`ls $1_* | cut -d '_' -f 2`)

for filename in ${FILES[*]}; do

   mv $1_$filename $2_$filename

done

echo '--| '
echo '--| Bye.'
echo '--| '
echo '--| '
