/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ParticlesToBBDD_TYPES_H
#define ParticlesToBBDD_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace BBDDParticles {

class Particle;

class InsertData;

class InsertResult;

typedef struct _Particle__isset {
  _Particle__isset() : time(false), partId(false), x(false), y(false), z(false), doubleProperties(false), intProperties(false) {}
  bool time :1;
  bool partId :1;
  bool x :1;
  bool y :1;
  bool z :1;
  bool doubleProperties :1;
  bool intProperties :1;
} _Particle__isset;

class Particle {
 public:

  static const char* ascii_fingerprint; // = "C029FD862DC112401DAF504F8CF488E0";
  static const uint8_t binary_fingerprint[16]; // = {0xC0,0x29,0xFD,0x86,0x2D,0xC1,0x12,0x40,0x1D,0xAF,0x50,0x4F,0x8C,0xF4,0x88,0xE0};

  Particle(const Particle&);
  Particle& operator=(const Particle&);
  Particle() : time(0), partId(0), x(0), y(0), z(0) {
  }

  virtual ~Particle() throw();
  double time;
  int32_t partId;
  double x;
  double y;
  double z;
  std::map<std::string, double>  doubleProperties;
  std::map<std::string, int32_t>  intProperties;

  _Particle__isset __isset;

  void __set_time(const double val);

  void __set_partId(const int32_t val);

  void __set_x(const double val);

  void __set_y(const double val);

  void __set_z(const double val);

  void __set_doubleProperties(const std::map<std::string, double> & val);

  void __set_intProperties(const std::map<std::string, int32_t> & val);

  bool operator == (const Particle & rhs) const
  {
    if (!(time == rhs.time))
      return false;
    if (!(partId == rhs.partId))
      return false;
    if (!(x == rhs.x))
      return false;
    if (!(y == rhs.y))
      return false;
    if (!(z == rhs.z))
      return false;
    if (!(doubleProperties == rhs.doubleProperties))
      return false;
    if (!(intProperties == rhs.intProperties))
      return false;
    return true;
  }
  bool operator != (const Particle &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Particle & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Particle& obj);
};

void swap(Particle &a, Particle &b);

typedef struct _InsertData__isset {
  _InsertData__isset() : data(false), time(false) {}
  bool data :1;
  bool time :1;
} _InsertData__isset;

class InsertData {
 public:

  static const char* ascii_fingerprint; // = "818AB2776FE035EBD499AA89B7256F96";
  static const uint8_t binary_fingerprint[16]; // = {0x81,0x8A,0xB2,0x77,0x6F,0xE0,0x35,0xEB,0xD4,0x99,0xAA,0x89,0xB7,0x25,0x6F,0x96};

  InsertData(const InsertData&);
  InsertData& operator=(const InsertData&);
  InsertData() : time(0) {
  }

  virtual ~InsertData() throw();
  std::vector<Particle>  data;
  int32_t time;

  _InsertData__isset __isset;

  void __set_data(const std::vector<Particle> & val);

  void __set_time(const int32_t val);

  bool operator == (const InsertData & rhs) const
  {
    if (!(data == rhs.data))
      return false;
    if (!(time == rhs.time))
      return false;
    return true;
  }
  bool operator != (const InsertData &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InsertData & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const InsertData& obj);
};

void swap(InsertData &a, InsertData &b);

typedef struct _InsertResult__isset {
  _InsertResult__isset() : sucess(false), error(false) {}
  bool sucess :1;
  bool error :1;
} _InsertResult__isset;

class InsertResult {
 public:

  static const char* ascii_fingerprint; // = "1767FFB0CB3D9275BC64B198AB3B8A8B";
  static const uint8_t binary_fingerprint[16]; // = {0x17,0x67,0xFF,0xB0,0xCB,0x3D,0x92,0x75,0xBC,0x64,0xB1,0x98,0xAB,0x3B,0x8A,0x8B};

  InsertResult(const InsertResult&);
  InsertResult& operator=(const InsertResult&);
  InsertResult() : sucess(0), error() {
  }

  virtual ~InsertResult() throw();
  bool sucess;
  std::string error;

  _InsertResult__isset __isset;

  void __set_sucess(const bool val);

  void __set_error(const std::string& val);

  bool operator == (const InsertResult & rhs) const
  {
    if (!(sucess == rhs.sucess))
      return false;
    if (!(error == rhs.error))
      return false;
    return true;
  }
  bool operator != (const InsertResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const InsertResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const InsertResult& obj);
};

void swap(InsertResult &a, InsertResult &b);

} // namespace

#endif
