/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ParticlesToBBDD_CONSTANTS_H
#define ParticlesToBBDD_CONSTANTS_H

#include "ParticlesToBBDD_types.h"

namespace BBDDParticles {

class ParticlesToBBDDConstants {
 public:
  ParticlesToBBDDConstants();

};

extern const ParticlesToBBDDConstants g_ParticlesToBBDD_constants;

} // namespace

#endif
